# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
#pipeline name
name: Node.js CD
#tr
on:
 #event1
  push:
    branches: [ "main" ]
    #event2
  

jobs:
  deploy:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: "Build Docker Image"
      run: docker build -t sushantjhingran/my-node-app:latest .
    - name: "Build Successfull"
      run: echo "Image created Successful"
    - name: "Login with docket cred"
      run: echo "${{secrets.pwd}}" | docker login -u sushantjhingran --password-stdin
    - name: "Push Docker Image"
      run: docker push sushantjhingran/my-node-app:latest
    - name: "Push Successfull"
      run: echo "Image pushed Successful"